/**
 * Regenerates docs/content-needs.md — the self-reranking "what to photograph next"
 * list for the Vivrelle rent-and-shoot pipeline.
 *
 *   Demand (scripts/content-needs/catalog.ts)  minus  captures (captured.csv)
 *   scored by bang-for-buck (surfaces filled ÷ Vivrelle tier cost)  =  ranked list.
 *
 * Run:  npm run content:needs
 * Update after a shoot: append one line to captured.csv (status shot|published),
 * then rerun — the closed bag drops off the top on its own. No DB, no creds.
 */
import fs from "fs";
import path from "path";
import { parse } from "csv-parse/sync";
import {
  NEEDS,
  SURFACE_LABEL,
  TIER_LABEL,
  bangForBuck,
  valueScore,
  type Need,
} from "./catalog";

interface Capture {
  brand: string;
  style: string;
  colorway: string;
  material: string;
  status: string; // in_hand | shot | published
  source: string;
  date: string;
  notes: string;
}

const DIR = __dirname;
const OUT = path.resolve(DIR, "../../docs/content-needs.md");
const GENERATED_ON = new Date().toISOString().slice(0, 10);

function readCaptures(): Capture[] {
  const csv = fs.readFileSync(path.resolve(DIR, "captured.csv"), "utf8");
  return parse(csv, { columns: true, skip_empty_lines: true, trim: true }) as Capture[];
}

const norm = (s: string): string => s.trim().toLowerCase();
const specText = (c: Capture): string => `${c.colorway} ${c.material}`;

function capturesFor(need: Need, captures: Capture[]): Capture[] {
  return captures.filter((c) => norm(c.brand) === norm(need.brand) && norm(c.style) === norm(need.style));
}

function specMatch(need: Need, c: Capture): boolean {
  return need.preferredSpec ? need.preferredSpec.test(specText(c)) : true;
}

type State = "closed" | "in_hand_closing" | "in_hand_partial" | "open";

function stateOf(need: Need, captures: Capture[]): State {
  const rows = capturesFor(need, captures);
  const closed = rows.some((c) => (c.status === "shot" || c.status === "published") && specMatch(need, c));
  if (closed) return "closed";
  const inHand = rows.filter((c) => c.status === "in_hand");
  if (inHand.some((c) => specMatch(need, c))) return "in_hand_closing";
  if (inHand.length > 0) return "in_hand_partial";
  return "open";
}

const fills = (need: Need): string => need.surfaces.map((s) => SURFACE_LABEL[s]).join(", ");
const score = (need: Need): string => `${bangForBuck(need).toFixed(1)} (value ${valueScore(need)})`;

function row(need: Need, extra?: string): string {
  const name = `${need.brand} ${need.style}`;
  const rank = need.homepageRank ? ` · homepage #${need.homepageRank}` : "";
  const note = [extra, need.note].filter(Boolean).join(" ");
  return `| ${name}${rank} | ${fills(need)} | ${TIER_LABEL[need.tier]} | ${score(need)} | ${note || "—"} |`;
}

const TABLE_HEAD = "| Bag | Fills | Vivrelle tier | Bang-for-buck | Note |\n|---|---|---|---|---|";

function main(): void {
  const captures = readCaptures();
  const withState = NEEDS.map((need) => ({ need, state: stateOf(need, captures) }));

  const inHand = withState.filter((x) => x.state === "in_hand_closing" || x.state === "in_hand_partial");

  const rentable = withState
    .filter((x) => (x.state === "open" || x.state === "in_hand_partial") && (x.need.tier === "Classique" || x.need.tier === "Couture"))
    .sort((a, b) => bangForBuck(b.need) - bangForBuck(a.need) || valueScore(b.need) - valueScore(a.need));

  const unconfirmed = withState
    .filter((x) => x.state === "open" && x.need.tier === "Unconfirmed")
    .sort((a, b) => bangForBuck(b.need) - bangForBuck(a.need));

  const gated = withState.filter((x) => x.state === "open" && x.need.tier === "Reserve");
  const notCarried = withState.filter((x) => x.state === "open" && x.need.tier === "NotCarried");

  const archived = captures
    .filter((c) => c.status === "shot" || c.status === "published")
    .sort((a, b) => a.brand.localeCompare(b.brand) || a.style.localeCompare(b.style));

  const L: string[] = [];
  L.push("# Content needs — what to photograph next");
  L.push("");
  L.push(`*Auto-generated by \`npm run content:needs\` (${GENERATED_ON}). Do not hand-edit — edit \`scripts/content-needs/catalog.ts\` (what the site needs) or \`scripts/content-needs/captured.csv\` (what's shot), then rerun.*`);
  L.push("");
  L.push("**How the ranking works.** Each bag scores by the surfaces it fills (a wired-but-empty compare-slideshow cutout is worth most, then seeded-auth / protective-feet heroes, then About cutouts and live search demand) plus a homepage-canon bonus, divided by the Vivrelle tier that unlocks it. So the top of the list is the most site value per rental dollar. As you shoot bags and log them, closed bags fall off the top on their own.");
  L.push("");
  L.push("> Vivrelle tiers/prices are from 2026 review sources (archivist pull 2026-07-07): Classique ~$139, Couture ~$239, Réservé/Privée ~$800 invite-only. Prices drift across sources; the checkout page is ground truth. This is our read, not a Vivrelle quote.");
  L.push("");

  L.push("## In hand now — shoot before you return them");
  L.push("");
  if (inHand.length === 0) {
    L.push("_Nothing checked out right now._");
  } else {
    L.push(TABLE_HEAD);
    for (const x of inHand) {
      const tag = x.state === "in_hand_closing" ? "IN HAND — closes this hero." : "IN HAND (off-marquee variant) — shoot it, but the marquee spec below stays open.";
      L.push(row(x.need, tag));
    }
  }
  L.push("");

  L.push("## Shoot next — rentable, ranked by bang-for-buck");
  L.push("");
  L.push(TABLE_HEAD);
  for (const x of rentable) {
    const tag = x.state === "in_hand_partial" ? "Marquee spec still open (the in-hand variant does not cover it)." : "";
    L.push(row(x.need, tag));
  }
  L.push("");

  if (unconfirmed.length > 0) {
    L.push("## Rentability unconfirmed — check the live closet first");
    L.push("");
    L.push(TABLE_HEAD);
    for (const x of unconfirmed) L.push(row(x.need));
    L.push("");
  }

  if (gated.length > 0) {
    L.push("## Gated — invite-only tier ($800/mo)");
    L.push("");
    L.push(TABLE_HEAD);
    for (const x of gated) L.push(row(x.need));
    L.push("");
  }

  if (notCarried.length > 0) {
    L.push("## Not via Vivrelle — source elsewhere (owned / Fashionphile / UGC)");
    L.push("");
    L.push(TABLE_HEAD);
    for (const x of notCarried) L.push(row(x.need));
    L.push("");
  }

  L.push(`## Already captured (${archived.length})`);
  L.push("");
  L.push("| Bag | Spec | Source | Date |\n|---|---|---|---|");
  for (const c of archived) {
    const spec = [c.colorway, c.material].filter((s) => s && s !== "various").join(" ") || "—";
    L.push(`| ${c.brand} ${c.style} | ${spec} | ${c.source} | ${c.date || "—"} |`);
  }
  L.push("");

  L.push("---");
  L.push("");
  L.push("### Update it");
  L.push("1. Shot a bag? Append a line to `scripts/content-needs/captured.csv` (`status` = `shot`; use `published` once it's live on the bag page).");
  L.push("2. Run `npm run content:needs`. The list re-ranks and the bag moves to *Already captured*.");
  L.push("3. Site added a new hero list, slideshow pairing, or cutout slot? Add/adjust the entry in `scripts/content-needs/catalog.ts` and rerun.");
  L.push("4. Later: the live 'Most Wanted Photos' want-count signal (`src/lib/photos.ts` `getMostWantedPhotos`) can plug in as another demand source once a service-role key is in the env.");
  L.push("");

  fs.writeFileSync(OUT, L.join("\n"));
  process.stdout.write(`Wrote ${OUT}\n`);
  process.stdout.write(`In hand: ${inHand.length} · Shoot-next: ${rentable.length} · Unconfirmed: ${unconfirmed.length} · Captured: ${archived.length}\n`);
}

main();
